stages:
  - linting
  - test

cpplint:
  stage: linting
  script:
    - sh tool/cpplint.sh

test:
  stage: test
  script:
    - bash tool/cmake-build-android-armeabi-v7a.sh
    - bash tool/cctest-android.sh
